export const verticals = [
  "Web App Development",
  "Mobile Development",
  "Web3",
  "Machine Learning",
  "Business Intelligence",
  "Product Design",
  "UX Research",
  "Content Marketing",
  "Game Development",
  "DevOps",
  "Cloud Architecture",
  "Cybersecurity",
  "Data Engineering",
  "SEO",
  "Social Media Marketing",
  "Customer Experience",
]

export const roles = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "UI/UX Designer",
  "Product Manager",
  "Data Scientist",
  "DevOps Engineer",
  "Mobile Developer",
  "Blockchain Developer",
  "UX Researcher",
  "Content Strategist",
  "SEO Specialist",
  "QA Engineer",
  "Technical Lead",
  "Project Manager",
  "Scrum Master",
]
