export const mockTalent = [
  {
    id: "1",
    name: "Alex Johnson",
    role: "Frontend Developer",
    avatar: "/confident-businessman.png",
    tagline: "I specialize in creating accessible, performant React applications",
    engagement: 95,
    area: "IT",
    highlightedSkill: {
      name: "Problem Solving",
      level: 92,
      icon: "brain",
    },
    projects: [
      { name: "FinFlow", color: "#FF5A5F" },
      { name: "EduLearn", color: "#00A699" },
    ],
    peerFeedback: "Alex consistently delivers clean code and is always willing to help teammates.",
  },
  {
    id: "2",
    name: "Sarah Chen",
    role: "Backend Developer",
    avatar: "/confident-asian-professional.png",
    tagline: "Building robust APIs and scalable database solutions",
    engagement: 88,
    area: "IT",
    highlightedSkill: {
      name: "Technical Leadership",
      level: 85,
      icon: "zap",
    },
    projects: [
      { name: "FinFlow", color: "#FF5A5F" },
      { name: "SecureChain", color: "#6B66FF" },
    ],
    peerFeedback: "Sarah's architecture decisions saved us countless hours of refactoring.",
  },
  {
    id: "3",
    name: "Miguel Rodriguez",
    role: "UI/UX Designer",
    avatar: "/confident-hispanic-professional.png",
    tagline: "Creating intuitive interfaces with a focus on user experience",
    engagement: 92,
    area: "Product",
    highlightedSkill: {
      name: "Empathy",
      level: 95,
      icon: "heart",
    },
    projects: [
      { name: "HealthTrack", color: "#4ECDC4" },
      { name: "EduLearn", color: "#00A699" },
    ],
    peerFeedback: "Miguel's designs are not only beautiful but incredibly thoughtful and user-centered.",
  },
  {
    id: "4",
    name: "Priya Patel",
    role: "Full Stack Developer",
    avatar: "/confident-indian-professional.png",
    tagline: "Bridging frontend and backend with TypeScript expertise",
    engagement: 90,
    area: "IT",
    highlightedSkill: {
      name: "Adaptability",
      level: 88,
      icon: "zap",
    },
    projects: [
      { name: "FinFlow", color: "#FF5A5F" },
      { name: "PredictX", color: "#7B68EE" },
    ],
    peerFeedback: "Priya quickly adapts to new technologies and always delivers high-quality work.",
  },
  {
    id: "5",
    name: "Emma Davis",
    role: "Mobile Developer",
    avatar: "/confident-professional-woman.png",
    tagline: "Crafting native-like experiences with React Native",
    engagement: 85,
    area: "IT",
    highlightedSkill: {
      name: "Innovation",
      level: 90,
      icon: "brain",
    },
    projects: [{ name: "HealthTrack", color: "#4ECDC4" }],
    peerFeedback: "Emma's creative solutions to complex mobile UI challenges impressed the entire team.",
  },
  {
    id: "6",
    role: "Data Scientist",
    name: "Robert Zhang",
    avatar: "/confident-asian-professional.png",
    tagline: "Turning data into actionable insights through ML models",
    engagement: 82,
    area: "Data",
    highlightedSkill: {
      name: "Analytical Thinking",
      level: 96,
      icon: "brain",
    },
    projects: [{ name: "PredictX", color: "#7B68EE" }],
    peerFeedback: "Robert's predictive models exceeded our expectations and delivered real business value.",
  },
  {
    id: "7",
    name: "Isabella Garcia",
    role: "UX Researcher",
    avatar: "/confident-hispanic-professional.png",
    tagline: "Uncovering user needs through methodical research",
    engagement: 94,
    area: "Product",
    highlightedSkill: {
      name: "Communication",
      level: 93,
      icon: "heart",
    },
    projects: [{ name: "EduLearn", color: "#00A699" }],
    peerFeedback: "Isabella's research insights completely transformed our product direction for the better.",
  },
  {
    id: "8",
    name: "Emily Wilson",
    role: "Content Strategist",
    avatar: "/confident-professional-woman.png",
    tagline: "Crafting compelling narratives that drive engagement",
    engagement: 88,
    area: "Marketing",
    highlightedSkill: {
      name: "Creativity",
      level: 91,
      icon: "zap",
    },
    projects: [{ name: "InsureTech", color: "#FF8C42" }],
    peerFeedback: "Emily's content strategy increased our conversion rates by 35% in just two months.",
  },
]
